/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import alertas.AlertaCorrecto;
import alertas.AlertaError;
import com.sun.awt.AWTUtilities;
import controladores.LugarControlador;
import static gestion.GestionLugar.comprimirImagen;

import grillas.GrillaLugar;
import java.awt.Image;
import java.awt.Window;
import java.awt.image.RenderedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.IIOImage;
import javax.imageio.ImageIO;
import javax.imageio.ImageWriteParam;
import javax.imageio.ImageWriter;
import javax.imageio.stream.ImageOutputStream;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;
import objetos.Lugar;
import static principal.Principal.escritorio;
import util.IABM;

/**
 *
 * @author Skylake
 */
public class ABMLugares extends javax.swing.JDialog implements IABM {

    private LugarControlador controlador = new LugarControlador();
    private Lugar lugar;
    private List<Lugar> list;

    private boolean ComprobarImagen = false;

    /**
     * Creates new form ABMLugares
     */
    public ABMLugares(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.jlRutaImagen.setVisible(false);
        this.jlId.setVisible(false);
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbCerrar13 = new rojeru_san.RSButtonRiple();
        jlTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jtfUbicacion = new rscomponentshade.RSFormatFieldShade();
        jtfEmail = new rscomponentshade.RSFormatFieldShade();
        jbNuevo = new rojeru_san.RSButtonRiple();
        rSPanelShadow3 = new rojeru_san.RSPanelShadow();
        jPanel5 = new javax.swing.JPanel();
        jlImagen = new javax.swing.JLabel();
        jbLimpiar = new rojeru_san.RSButtonRiple();
        jbSeleccionarImagen = new rojeru_san.RSButtonRiple();
        jtfNombreLugar = new rscomponentshade.RSTextFieldShade();
        jlRutaImagen = new javax.swing.JLabel();
        jlId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 124, 0));

        jPanel2.setBackground(new java.awt.Color(245, 124, 0));

        jbCerrar13.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrar13.setText("X");
        jbCerrar13.setColorHover(new java.awt.Color(255, 152, 0));
        jbCerrar13.setColorText(new java.awt.Color(245, 124, 0));
        jbCerrar13.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jbCerrar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrar13ActionPerformed(evt);
            }
        });

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("REGISTRAR NUEVO LUGAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ESTADO");

        jrbActivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbActivo);
        jrbActivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbActivo.setText("ACTIVADO");

        jrbInactivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbInactivo);
        jrbInactivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbInactivo.setText("INACTIVO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jrbInactivo))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbActivo)
                    .addComponent(jrbInactivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jtfUbicacion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfUbicacion.setPlaceholder("UBICACIÓN");
        jtfUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUbicacionActionPerformed(evt);
            }
        });

        jtfEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfEmail.setPlaceholder("EMAIL");
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(245, 124, 0));
        jbNuevo.setText("REGISTRAR");
        jbNuevo.setColorHover(new java.awt.Color(255, 152, 0));
        jbNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jlImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );

        rSPanelShadow3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jbLimpiar.setBackground(new java.awt.Color(245, 124, 0));
        jbLimpiar.setText("LIMPIAR CAMPOS");
        jbLimpiar.setColorHover(new java.awt.Color(255, 152, 0));
        jbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbSeleccionarImagen.setBackground(new java.awt.Color(245, 124, 0));
        jbSeleccionarImagen.setText("SELECCIONAR IMAGEN");
        jbSeleccionarImagen.setColorHover(new java.awt.Color(255, 152, 0));
        jbSeleccionarImagen.setFocusable(false);
        jbSeleccionarImagen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbSeleccionarImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeleccionarImagenActionPerformed(evt);
            }
        });

        jtfNombreLugar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfNombreLugar.setPlaceholder("NOMBRE DEL LUGAR");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rSPanelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNombreLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlRutaImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jlId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rSPanelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSeleccionarImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSeleccionarImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtfUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlRutaImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrar13ActionPerformed
        GestionLugares gestionLugares = null;
        try {
            gestionLugares = new GestionLugares();
            gestionLugares.ActualizarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(ABMLugares.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jbCerrar13ActionPerformed

    private void jtfUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUbicacionActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        if (comprobarErrores() == IABM.error) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("DEBE COMPLETAR EL FORMULARIO");
            alertaError.setVisible(true);
            /* } else if (ComprobarImagen == false) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("DEBE SELECCIONAR UNA IMAGEN");
            alertaError.setVisible(true);*/
        } else if (grabar() == IABM.ok) {
            
            /* AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
            alertaCorrecto.jlCorrecto.setText("SE REGISTRO CORRECTAMENTE");
            alertaCorrecto.setVisible(true);*/

            try {
                GestionLugares gestionLugares = new GestionLugares();
                escritorio.removeAll();
                gestionLugares = new GestionLugares(); // TODO add your handling code here:
                int width = escritorio.getWidth();
                int Height = escritorio.getHeight();
                gestionLugares.setSize(width, Height);
                escritorio.add(gestionLugares);
                gestionLugares.show();

            } catch (Exception e) {
            }
        }
        /*else if (grabar() == IABM.nok) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("ERROR AL REGISTRAR");
            alertaError.setVisible(true);
        }*/
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        inicio(); // TODO add your handling code here:
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbSeleccionarImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeleccionarImagenActionPerformed
        // TODO add your handling code here:
        //Creamos nuestra variable archivo en la cual podremos usar todos los metodos de la clase jFileChooser
        JFileChooser archivo = new JFileChooser();
        //Si deseamos crear filtros para la selecion de archivos
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg", "jpeg");
        //Si deseas que se muestre primero los filtros usa la linea q esta abajo de esta.
        //archivo.setFileFilter(filtro);
        // Agregamos el Filtro pero cuidado se mostrara despues de todos los archivos
        archivo.setAcceptAllFileFilterUsed(false);
        archivo.addChoosableFileFilter(filtro);
        // Colocamos titulo a nuestra ventana de Seleccion
        archivo.setDialogTitle("Abrir Archivo");
        //Si deseamos que muestre una carpeta predetermina usa la siguiente linea
        // File ruta = new File("D:/productos");
        //Le implementamos a nuestro ventana de seleccion
        //   archivo.setCurrentDirectory(ruta);
        //Abrimos nuestra Ventana de Selccion
        int ventana = archivo.showOpenDialog(null);

        if (ventana == JFileChooser.APPROVE_OPTION) {
            //Obtenemos la ruta de nuestra imagen seleccionada
            File file = archivo.getSelectedFile();
            String ruta = String.valueOf(file);
            //Lo imprimimos en una caja de texto para ver su ruta

            //de cierto modo necesitamos tener la imagen para ello debemos conocer la ruta de dicha imagen
            Image foto = getToolkit().getImage(ruta);
            foto = foto.getScaledInstance(jlImagen.getWidth(), jlImagen.getHeight(), Image.SCALE_SMOOTH);
            //Le damos dimension a nuestro label que tendra la imagen
            //   foto= foto.getScaledInstance(110, 110, Image.SCALE_DEFAULT);
            //Imprimimos la imagen en el label
            Random generadorNumero = new Random();
            int numeroAleatorio = 1 + generadorNumero.nextInt(1000000);
            File destino = new File("D:\\Documentos\\securityImagenes\\" + numeroAleatorio + ".jpg");
            try {

                comprimirImagen(file, destino, 0.5f);
                String ruta2 = String.valueOf(destino);

                jlRutaImagen.setText(ruta2);
            } catch (IOException ex) {
                Logger.getLogger(GestionLugar.class.getName()).log(Level.SEVERE, null, ex);
            }

            jlImagen.setIcon(new ImageIcon(foto));
            ComprobarImagen = true;
        } else {
            ComprobarImagen = false;
        }
    }//GEN-LAST:event_jbSeleccionarImagenActionPerformed

    public static void comprimirImagen(File original, File destino, float calidad) throws IOException {
        RenderedImage imagen = ImageIO.read(original);
        ImageWriter jpegWrite = ImageIO.getImageWritersByFormatName("jpg").next();
        ImageWriteParam jpgWriteParam = jpegWrite.getDefaultWriteParam();
        jpgWriteParam.setCompressionMode(ImageWriteParam.MODE_EXPLICIT);
        jpgWriteParam.setCompressionQuality(calidad);
        try (ImageOutputStream output = ImageIO.createImageOutputStream(destino)) {
            jpegWrite.setOutput(output);
            IIOImage outputImage = new IIOImage(imagen, null, null);
            jpegWrite.write(null, outputImage, jpgWriteParam);
        }
        jpegWrite.dispose();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            /*  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }*/
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionLugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /*     try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMLugares.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }*/
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMLugares dialog = new ABMLugares(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojeru_san.RSButtonRiple jbCerrar13;
    public rojeru_san.RSButtonRiple jbLimpiar;
    public rojeru_san.RSButtonRiple jbNuevo;
    private rojeru_san.RSButtonRiple jbSeleccionarImagen;
    public javax.swing.JLabel jlId;
    public javax.swing.JLabel jlImagen;
    public javax.swing.JLabel jlRutaImagen;
    public static javax.swing.JLabel jlTitulo;
    public javax.swing.JRadioButton jrbActivo;
    public javax.swing.JRadioButton jrbInactivo;
    public rscomponentshade.RSFormatFieldShade jtfEmail;
    public rscomponentshade.RSTextFieldShade jtfNombreLugar;
    public rscomponentshade.RSFormatFieldShade jtfUbicacion;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelShadow rSPanelShadow3;
    // End of variables declaration//GEN-END:variables

    @Override
    public int grabar() {
        if (jbNuevo.getText().equals("REGISTRAR")) {
            lugar = new Lugar();
            lugar.setNombreLugar(jtfNombreLugar.getText());
            lugar.setUbicacion(jtfUbicacion.getText());
            lugar.setEmail(jtfEmail.getText());
            if (jrbActivo.isSelected()) {
                lugar.setEstado("1");
            } else {
                lugar.setEstado("0");
            }
            if (ComprobarImagen == false) {
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("DEBE SELECCIONAR UNA IMAGEN");
                alertaError.setVisible(true);
            }
            File ruta = new File(jlRutaImagen.getText());
            byte[] icono = new byte[(int) ruta.length()];
            try {
                InputStream input = new FileInputStream(ruta);
                input.read(icono);
                lugar.setImagen(icono);
                controlador.insetar(lugar);
                AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
                alertaCorrecto.jlCorrecto.setText("SE REGISTRO CORRECTAMENTE");
                alertaCorrecto.setVisible(true);
                inicio();
            } catch (Exception ex) {
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("ERROR AL REGISTRAR");
                alertaError.setVisible(true);
            }
            return IABM.ok;
        } 
        
        else if (jbNuevo.getText().equals("MODIFICAR")) {
            lugar = new Lugar();
            lugar.setNombreLugar(jtfNombreLugar.getText());
            lugar.setUbicacion(jtfUbicacion.getText());
            lugar.setEmail(jtfEmail.getText());
            if (jrbActivo.isSelected()) {
                lugar.setEstado("1");
            } else {
                lugar.setEstado("0");
            }
            lugar.setIdLugares(Integer.parseInt(this.jlId.getText()));
            if (!jlRutaImagen.getText().equals("")) {
                File ruta = new File(jlRutaImagen.getText());

                byte[] icono = new byte[(int) ruta.length()];
                try {
                    InputStream input = new FileInputStream(ruta);
                    input.read(icono);
                    lugar.setImagen(icono);
                    controlador.modificar(lugar);
                    AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
                    alertaCorrecto.jlCorrecto.setText("SE MODIFICÓ CORRECTAMENTE");
                    alertaCorrecto.setVisible(true);
                } catch (Exception ex) {
                    AlertaError alertaError = new AlertaError(new JFrame(), true);
                    alertaError.jlError.setText("ERROR AL MODIFICAR");
                    alertaError.setVisible(true);
                }

                return IABM.ok;
            } else {
                try {
                    ComprobarImagen = true;
                    controlador.modificarSinImagen(lugar);
                    AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
                    alertaCorrecto.jlCorrecto.setText("SE MODIFICÓ CORRECTAMENTE");
                    alertaCorrecto.setVisible(true);
                } catch (SQLException ex) {
                    AlertaError alertaError = new AlertaError(new JFrame(), true);
                    alertaError.jlError.setText("ERROR AL MODIFICAR");
                    alertaError.setVisible(true);

                }
                return IABM.ok;
            }

        }
        return IABM.nok;
    }

    @Override
    public int comprobarErrores() {
        if (jtfNombreLugar.getText().trim().isEmpty() || jtfUbicacion.getText().trim().isEmpty() || jtfEmail.getText().trim().isEmpty()) {
            return IABM.error;
        }
        if (jrbActivo.isSelected() == false && jrbInactivo.isSelected() == false) {
            return IABM.error;
        }
        return IABM.ok;
    }

    @Override
    public void inicio() {
        jtfNombreLugar.setText("");
        jtfUbicacion.setText("");
        jtfEmail.setText("");
        jlImagen.setIcon(null);
        jlRutaImagen.setText(null);
        ComprobarImagen = false;
    }

    @Override
    public void actualizar() {

    }
}
