/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import alertas.AlertaCorrecto;
import alertas.AlertaError;
import controladores.PersonalAutorizadoControl;
import controladores.UsuarioControlador;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import objetos.PersonalAutorizado;
import objetos.Usuario;
import static principal.Principal.escritorio;
import util.IABM;

/**
 *
 * @author Skylake
 */
public class ABMUsuario extends javax.swing.JDialog implements IABM {

    private UsuarioControlador controlador = new UsuarioControlador();
    private Usuario usuario;
    private List<Usuario> list;
    private boolean ComprobarImagen = false;

    /**
     * Creates new form ABMUsuario
     */
    public ABMUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setUndecorated(true);
        initComponents();
        this.jlId.setVisible(true);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbCerrar13 = new rojeru_san.RSButtonRiple();
        jlTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jrbActivo = new javax.swing.JRadioButton();
        jrbInactivo = new javax.swing.JRadioButton();
        jtApellido = new rscomponentshade.RSFormatFieldShade();
        jtfDni = new rscomponentshade.RSFormatFieldShade();
        jbNuevo = new rojeru_san.RSButtonRiple();
        jbLimpiar = new rojeru_san.RSButtonRiple();
        jtfNombre = new rscomponentshade.RSTextFieldShade();
        jlId = new javax.swing.JLabel();
        jtfEmail = new rscomponentshade.RSTextFieldShade();
        jtfUser = new rscomponentshade.RSFormatFieldShade();
        jtfPass = new rscomponentshade.RSFormatFieldShade();
        jtfDireccion = new rscomponentshade.RSFormatFieldShade();
        jtfTelefono = new rscomponentshade.RSFormatFieldShade();
        rSPanelShadow3 = new rojeru_san.RSPanelShadow();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jrbAdministrador = new javax.swing.JRadioButton();
        jrbGuardia = new javax.swing.JRadioButton();
        jrbSupervisor = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(245, 124, 0));

        jPanel2.setBackground(new java.awt.Color(245, 124, 0));

        jbCerrar13.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrar13.setText("X");
        jbCerrar13.setColorHover(new java.awt.Color(255, 152, 0));
        jbCerrar13.setColorText(new java.awt.Color(245, 124, 0));
        jbCerrar13.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jbCerrar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrar13ActionPerformed(evt);
            }
        });

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("REGISTRAR NUEVO LUGAR");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("ESTADO");

        jrbActivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbActivo);
        jrbActivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbActivo.setText("ACTIVADO");

        jrbInactivo.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jrbInactivo);
        jrbInactivo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbInactivo.setText("INACTIVO");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jrbActivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(jrbInactivo))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbActivo)
                    .addComponent(jrbInactivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jtApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtApellido.setPlaceholder("APELLIDO");
        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        jtfDni.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfDni.setPlaceholder("DNI");
        jtfDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDniActionPerformed(evt);
            }
        });

        jbNuevo.setBackground(new java.awt.Color(245, 124, 0));
        jbNuevo.setText("REGISTRAR");
        jbNuevo.setColorHover(new java.awt.Color(255, 152, 0));
        jbNuevo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbLimpiar.setBackground(new java.awt.Color(245, 124, 0));
        jbLimpiar.setText("LIMPIAR CAMPOS");
        jbLimpiar.setColorHover(new java.awt.Color(255, 152, 0));
        jbLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jtfNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfNombre.setPlaceholder("NOMBRE");
        jtfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreActionPerformed(evt);
            }
        });

        jtfEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfEmail.setPlaceholder("EMAIL");

        jtfUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfUser.setPlaceholder("USER");
        jtfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUserActionPerformed(evt);
            }
        });

        jtfPass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfPass.setPlaceholder("PASS");
        jtfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPassActionPerformed(evt);
            }
        });

        jtfDireccion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfDireccion.setPlaceholder("DIRECCIÓN");
        jtfDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDireccionActionPerformed(evt);
            }
        });

        jtfTelefono.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfTelefono.setPlaceholder("TELEFONO");
        jtfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTelefonoActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("ESTADO");

        jrbAdministrador.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jrbAdministrador);
        jrbAdministrador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbAdministrador.setText("ADMINISTRADOR");
        jrbAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbAdministradorActionPerformed(evt);
            }
        });

        jrbGuardia.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jrbGuardia);
        jrbGuardia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbGuardia.setText("GUARDIA");

        jrbSupervisor.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(jrbSupervisor);
        jrbSupervisor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jrbSupervisor.setText("SUPERVISOR");
        jrbSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSupervisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jrbAdministrador)
                .addGap(18, 18, 18)
                .addComponent(jrbSupervisor)
                .addGap(18, 18, 18)
                .addComponent(jrbGuardia)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbAdministrador)
                    .addComponent(jrbGuardia)
                    .addComponent(jrbSupervisor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rSPanelShadow3.add(jPanel5, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rSPanelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbNuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSPanelShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        rSPanelShadow1.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrar13ActionPerformed

        dispose();
    }//GEN-LAST:event_jbCerrar13ActionPerformed

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void jtfDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDniActionPerformed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        if (comprobarErrores() == IABM.error) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("DEBE COMPLETAR EL FORMULARIO");
            alertaError.setVisible(true);
            /* } else if (ComprobarImagen == false) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("DEBE SELECCIONAR UNA IMAGEN");
            alertaError.setVisible(true);*/
        } else if (grabar() == IABM.ok) {

            /* AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
            alertaCorrecto.jlCorrecto.setText("SE REGISTRO CORRECTAMENTE");
            alertaCorrecto.setVisible(true);*/
            try {
                GestionUsuarios gestionUsuarios = new GestionUsuarios();
                escritorio.removeAll();
                gestionUsuarios = new GestionUsuarios(); // TODO add your handling code here:
                int width = escritorio.getWidth();
                int Height = escritorio.getHeight();
                gestionUsuarios.setSize(width, Height);
                escritorio.add(gestionUsuarios);
                gestionUsuarios.show();

            } catch (Exception e) {
            }
        }
        /*else if (grabar() == IABM.nok) {
            AlertaError alertaError = new AlertaError(new JFrame(), true);
            alertaError.jlError.setText("ERROR AL REGISTRAR");
            alertaError.setVisible(true);
        }*/
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        inicio(); // TODO add your handling code here:
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jtfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUserActionPerformed

    private void jtfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPassActionPerformed

    private void jtfDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDireccionActionPerformed

    private void jtfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTelefonoActionPerformed

    private void jrbAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbAdministradorActionPerformed

    private void jrbSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbSupervisorActionPerformed

    private void jtfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABMUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABMUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABMUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABMUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ABMUsuario dialog = new ABMUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private rojeru_san.RSButtonRiple jbCerrar13;
    public rojeru_san.RSButtonRiple jbLimpiar;
    public rojeru_san.RSButtonRiple jbNuevo;
    public javax.swing.JLabel jlId;
    public static javax.swing.JLabel jlTitulo;
    public javax.swing.JRadioButton jrbActivo;
    public javax.swing.JRadioButton jrbAdministrador;
    public javax.swing.JRadioButton jrbGuardia;
    public javax.swing.JRadioButton jrbInactivo;
    public javax.swing.JRadioButton jrbSupervisor;
    public rscomponentshade.RSFormatFieldShade jtApellido;
    public rscomponentshade.RSFormatFieldShade jtfDireccion;
    public rscomponentshade.RSFormatFieldShade jtfDni;
    public rscomponentshade.RSTextFieldShade jtfEmail;
    public rscomponentshade.RSTextFieldShade jtfNombre;
    public rscomponentshade.RSFormatFieldShade jtfPass;
    public rscomponentshade.RSFormatFieldShade jtfTelefono;
    public rscomponentshade.RSFormatFieldShade jtfUser;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelShadow rSPanelShadow3;
    // End of variables declaration//GEN-END:variables

    @Override
    public int grabar() {
        if (jbNuevo.getText().equals("REGISTRAR")) {
            usuario = new Usuario();
            usuario.setNombre(jtfNombre.getText());
            usuario.setApellida(jtApellido.getText());
            usuario.setDni(jtfDni.getText());
            usuario.setDireccion(jtfDireccion.getText());
            usuario.setTelefono(jtfTelefono.getText());
            usuario.setUser(jtfUser.getText());
            usuario.setPass(jtfPass.getText());
            usuario.setEmail(jtfEmail.getText());
            if (jrbAdministrador.isSelected()) {
                usuario.setTipoUsuario("administrador");
            } else if (jrbSupervisor.isSelected()) {
                usuario.setTipoUsuario("supervisor");

            } else if (jrbGuardia.isSelected()) {
                usuario.setTipoUsuario("guardia");

            }
            if (jrbActivo.isSelected()) {
                usuario.setEstado("1");
            } else {
                usuario.setEstado("0");
            }

            try {
                controlador.insetar(usuario);
                AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
                alertaCorrecto.jlCorrecto.setText("SE REGISTRO CORRECTAMENTE");
                alertaCorrecto.setVisible(true);
                inicio();
            } catch (SQLException ex) {
                Logger.getLogger(ABMPersonalAutirozado.class.getName()).log(Level.SEVERE, null, ex);
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("ERROR AL REGISTRAR");
                alertaError.setVisible(true);
            }

            return IABM.ok;
        } else if (jbNuevo.getText().equals("MODIFICAR")) {
            usuario = new Usuario();
            usuario.setNombre(jtfNombre.getText());
            usuario.setApellida(jtApellido.getText());
            usuario.setDni(jtfDni.getText());
            usuario.setDireccion(jtfDireccion.getText());
            usuario.setTelefono(jtfTelefono.getText());
            usuario.setUser(jtfUser.getText());
            usuario.setPass(jtfPass.getText());
            usuario.setEmail(jtfEmail.getText());
            if (jrbAdministrador.isSelected()) {
                usuario.setTipoUsuario("administrador");
            } else if (jrbSupervisor.isSelected()) {
                usuario.setTipoUsuario("supervisor");

            } else if (jrbGuardia.isSelected()) {
                usuario.setTipoUsuario("guardia");

            }
            if (jrbActivo.isSelected()) {
                usuario.setEstado("1");
            } else {
                usuario.setEstado("0");
            }
            usuario.setIdPersona(Long.parseLong(this.jlId.getText()));

            try {

                controlador.modificar(usuario);
                AlertaCorrecto alertaCorrecto = new AlertaCorrecto(new JFrame(), true);
                alertaCorrecto.jlCorrecto.setText("SE MODIFICÓ CORRECTAMENTE");
                alertaCorrecto.setVisible(true);
            } catch (Exception ex) {
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("ERROR AL MODIFICAR");
                alertaError.setVisible(true);
            }

            return IABM.ok;
        }

        return IABM.nok;
    }

    @Override
    public int comprobarErrores() {
        if (jtfNombre.getText().trim().isEmpty() || jtApellido.getText().trim().isEmpty() || jtfDni.getText().trim().isEmpty()
            || jtfDireccion.getText().trim().isEmpty() || jtfEmail.getText().trim().isEmpty() || jtfPass.getText().trim().isEmpty()
                || jtfUser.getText().trim().isEmpty() || jtfTelefono.getText().trim().isEmpty()) {
            return IABM.error;
        }
        if (jrbActivo.isSelected() == false && jrbInactivo.isSelected() == false) {
            return IABM.error;
        }
        return IABM.ok;
    }

    @Override
    public void inicio() {
        jtfNombre.setText("");
        jtApellido.setText("");
        jtfDni.setText("");
        jtfDireccion.setText("");
        jtfEmail.setText("");
        jtfPass.setText("");
        jtfUser.setText("");
        jtfTelefono.setText("");

    }

    @Override
    public void actualizar() {

    }
}
