/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import alertas.AlertaError;
import alertas.Cargando;
import com.mysql.jdbc.Connection;
import controladores.InformeControl;
import controladores.LugarControlador;
import static gestion.ABMLugares.comprimirImagen;
import grillas.GrillaControl;
import grillas.GrillaInforme;
import grillas.GrillaLugar;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.Shape;
import java.awt.geom.AffineTransform;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRPrintPage;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import objetos.Control;
import objetos.Informe;
import objetos.Lugar;
import rojerusan.componentes.RSProgressCircleAnimated;
import util.conexion;
import util.fecha;

/**
 *
 * @author Skylake
 */
public class GestionInformes extends javax.swing.JInternalFrame {

    private GrillaInforme grillaInforme;
    private InformeControl controlador = new InformeControl();
    private Informe informe;
    private List<Informe> list;

    /**
     * Creates new form GestionInformes
     */
    public GestionInformes() throws SQLException {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        ActualizarTabla();
        jlImagen4.setVisible(false);
    }

    public void ActualizarTabla() throws SQLException {
        List<Informe> ca = controlador.extraertodo();
        try {
            grillaInforme = new GrillaInforme((ArrayList<Informe>) ca);
            //jtabla2.setModel(grillaLugar);
            jtLugares.setModel(grillaInforme);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpadre = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jbCerrar13 = new rojeru_san.RSButtonRiple();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLugares = new rojerusan.RSTableMetro();
        jPanel17 = new javax.swing.JPanel();
        jbModificar = new rojeru_san.RSButtonRiple();
        jbReporte = new rojeru_san.RSButtonRiple();
        jbEliminar = new rojeru_san.RSButtonRiple();
        jtfBuscar = new rscomponentshade.RSTextFieldShade();
        jPanel18 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel20 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlGuardia = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlInforme = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        rSPanelShadow6 = new rojeru_san.RSPanelShadow();
        rotador = new javax.swing.JPanel();
        jlImagen4 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        jpadre.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(245, 124, 0));

        jbCerrar13.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrar13.setText("X");
        jbCerrar13.setColorHover(new java.awt.Color(255, 152, 0));
        jbCerrar13.setColorText(new java.awt.Color(245, 124, 0));
        jbCerrar13.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jbCerrar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrar13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 124, 0));

        jtLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtLugares.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        jtLugares.setColorBordeFilas(new java.awt.Color(245, 124, 0));
        jtLugares.setColorBordeHead(new java.awt.Color(245, 124, 0));
        jtLugares.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        jtLugares.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jtLugares.setColorForegroundHead(new java.awt.Color(245, 124, 0));
        jtLugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLugaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLugares);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jbModificar.setBackground(new java.awt.Color(245, 124, 0));
        jbModificar.setText("BUSCAR");
        jbModificar.setColorHover(new java.awt.Color(255, 152, 0));
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbReporte.setBackground(new java.awt.Color(245, 124, 0));
        jbReporte.setText("REPORTES");
        jbReporte.setColorHover(new java.awt.Color(255, 152, 0));
        jbReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReporteActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(245, 124, 0));
        jbEliminar.setText("DESCARGAR IMAGEN");
        jbEliminar.setColorHover(new java.awt.Color(255, 152, 0));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtfBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBuscar.setPlaceholder("BUSCAR");
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jbReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("GUARDIA:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("LUGAR:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("FECHA:");

        jlGuardia.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("INFORME:");

        jlFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlLugar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlInforme.setEditable(false);
        jlInforme.setColumns(20);
        jlInforme.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlInforme.setRows(5);
        jlInforme.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(jlInforme);

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlGuardia, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlGuardia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        rSPanelShadow2.add(jPanel20, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSPanelShadow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        rotador.setBackground(new java.awt.Color(255, 255, 255));

        jlImagen4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout rotadorLayout = new javax.swing.GroupLayout(rotador);
        rotador.setLayout(rotadorLayout);
        rotadorLayout.setHorizontalGroup(
            rotadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
        );
        rotadorLayout.setVerticalGroup(
            rotadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen4, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        rSPanelShadow6.add(rotador, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow6, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow6, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpadreLayout = new javax.swing.GroupLayout(jpadre);
        jpadre.setLayout(jpadreLayout);
        jpadreLayout.setHorizontalGroup(
            jpadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpadreLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jpadreLayout.setVerticalGroup(
            jpadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpadreLayout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpadreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpadreLayout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpadre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrar13ActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrar13ActionPerformed

    private void jtLugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLugaresMouseClicked
        rotador.removeAll();
        rotador.repaint();
        if (jtLugares.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UNA FILA EN LA TABLA", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            informe = grillaInforme.getLugar(jtLugares.getSelectedRow());
            byte[] blob = informe.getImagen();
            {
                BufferedImage img = null;
                InputStream in = new ByteArrayInputStream(blob);
                try {
                    img = ImageIO.read(in);
                } catch (IOException ex) {
                    Logger.getLogger(GestionLugares.class.getName()).log(Level.SEVERE, null, ex);
                }
                //   rotador.removeAll();
                JLabel jLabel = new JLabel();
                jLabel.setSize(rotador.getWidth(), rotador.getHeight());
                jLabel.setVisible(true);
                Image newimage = img.getScaledInstance(rotador.getWidth(), rotador.getHeight(), Image.SCALE_SMOOTH);
                
                rotador.add(jLabel);
                ImageIcon icon = new ImageIcon(newimage);
                // rotador.add(jLabel);
                // JLabel jlabel = new JLabel(lugar.getNombreLugar());
                jLabel.setIcon(icon);

                //jlNombreLugar.setSize(jlNombreLugar.getPreferredSize());
                // jlNombreLugar.setText(lugar.getNombreLugar());
                jlGuardia.setText(informe.getControl().getUsuario().getNombre() + " " + informe.getControl().getUsuario().getApellida());
                //jlNombreLugar.setText(lugar.getNombreLugar());
                // jlNombreLugar.validate();
                jlLugar.setText(informe.getControl().getLugar().getNombreLugar());
                try {
                    jlFecha.setText(fecha.fdate(informe.getControl().getFechaHora()));
                } catch (ParseException ex) {
                    Logger.getLogger(GestionInformes.class.getName()).log(Level.SEVERE, null, ex);
                }

                jlInforme.setText(informe.getInforme());

                //jTextArea1.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jtLugaresMouseClicked

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed


        /* try {
            buscar();
        } catch (SQLException ex) {
            Logger.getLogger(GestionInformes.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReporteActionPerformed
        boolean estado = false;
          /* RSProgressCircleAnimated animated = new RSProgressCircleAnimated();
           animated.setSize(100, 100);
            animated.setVisible(true);
            animated.setLocation(jpadre.getWidth()/2,jpadre.getHeight()/2);
            
            jpadre.add(animated,0);*/
        try {
            conexion mysql = new conexion();
            java.sql.Connection conexion = mysql.conectar();

            JasperReport reporte = null;
            String path = "D:\\Documentos\\NetBeansProjects\\SecurityDesktop\\SecurityDesktop\\src\\reportes\\informes.jasper";

            Map parametro = new HashMap();
            parametro.put("idinforme", 7);

            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);

            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conexion);
            List<JRPrintPage> pages = jprint.getPages();

            if (pages.size() == 0) {
                AlertaError er = new AlertaError(new JFrame(), true);
                er.jlError.setText("NO");
                er.setVisible(true);
       
            } else {
                JasperViewer view = new JasperViewer(jprint, false);

                view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

                view.setVisible(true);
            }

        } catch (JRException ex) {
            Logger.getLogger(GestionInformes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbReporteActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (this.jtLugares.getRowCount() < 1) {
            AlertaError er = new AlertaError(new JFrame(), true);
            er.jlError.setText("LA TABLA ESTA VACÍA");
            er.setVisible(true);
        } else {
            if (this.jtLugares.getSelectedRowCount() < 1) {
                AlertaError er = new AlertaError(new JFrame(), true);
                er.jlError.setText("SELECCIONA UN REGISTRO");
                er.setVisible(true);
            } else {
                informe = grillaInforme.getLugar(jtLugares.getSelectedRow());
                Random generadorNumero = new Random();
                int numeroAleatorio = 1 + generadorNumero.nextInt(1000000);
                JFileChooser archivo = new JFileChooser();
                archivo.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                archivo.setApproveButtonText("Seleccionar");
                archivo.setAcceptAllFileFilterUsed(false);
                archivo.setDialogTitle("Seleccione destino");
                int ventana = archivo.showOpenDialog(null);
                byte[] blob = informe.getImagen();

                if (ventana == JFileChooser.APPROVE_OPTION) {
                    File di = archivo.getSelectedFile();
                    String ruta = String.valueOf(di);
                    try {
                        FileOutputStream fos = new FileOutputStream(ruta + "\\" + numeroAleatorio + ".jpg");
                        fos.write(blob);
                        File id = new File(ruta + "\\" + numeroAleatorio + ".jpg");
                        Desktop d = null;
                        d = Desktop.getDesktop();
                        d.open(id);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(GestionInformes.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(GestionInformes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    AlertaError er = new AlertaError(new JFrame(), true);
                    er.jlError.setText("SELECCIONe UNA CARPETA");
                    er.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyReleased

    }//GEN-LAST:event_jtfBuscarKeyReleased

    public void buscar() throws SQLException {
        List<Informe> ca = null;
        String variable = jtfBuscar.getText();
        if (!variable.isEmpty() && Character.isDigit(variable.charAt(0))) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

                Date a = sdf.parse(variable);
                SimpleDateFormat fmtOut = new SimpleDateFormat("yyyy-MM-dd");
                String b = fmtOut.format(a);

                ca = controlador.buscarfecha(b);

                grillaInforme = new GrillaInforme((ArrayList<Informe>) ca);
                //jtabla2.setModel(grillaLugar);
                jtLugares.setModel(grillaInforme);

            } catch (ParseException ex) {
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("Fecha Incorrecta");
                alertaError.setVisible(true);
                Logger.getLogger(GestionControles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ca = controlador.buscar(variable);

            grillaInforme = new GrillaInforme((ArrayList<Informe>) ca);
            //jtabla2.setModel(grillaLugar);
            jtLugares.setModel(grillaInforme);

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private rojeru_san.RSButtonRiple jbCerrar13;
    private rojeru_san.RSButtonRiple jbEliminar;
    private rojeru_san.RSButtonRiple jbModificar;
    private rojeru_san.RSButtonRiple jbReporte;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlGuardia;
    private javax.swing.JLabel jlImagen4;
    private javax.swing.JTextArea jlInforme;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JPanel jpadre;
    public rojerusan.RSTableMetro jtLugares;
    private rscomponentshade.RSTextFieldShade jtfBuscar;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    private rojeru_san.RSPanelShadow rSPanelShadow6;
    private javax.swing.JPanel rotador;
    // End of variables declaration//GEN-END:variables
}
