/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion;

import alertas.AlertaError;
import controladores.ControlControlador;
import controladores.PersonalAutorizadoControl;
import grillas.GrillaControl;
import grillas.GrillaPersonalAutorizado;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.URL;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import objetos.Control;
import objetos.PersonalAutorizado;
import util.fecha;

/**
 *
 * @author Skylake
 */
public class GestionControles extends javax.swing.JInternalFrame {

    private GrillaControl grillaControl;
    private ControlControlador controlador = new ControlControlador();
    private Control control;
    private List<Control> list;

    /**
     * Creates new form GestionControles
     */
    public GestionControles() throws SQLException {
        initComponents();
        ActualizarTabla();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
    }

    public void ActualizarTabla() throws SQLException {
        List<Control> ca = controlador.extraertodo();
        try {
            grillaControl = new GrillaControl((ArrayList<Control>) ca);
            //jtabla2.setModel(grillaLugar);
            jtLugares.setModel(grillaControl);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jbCerrar13 = new rojeru_san.RSButtonRiple();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLugares = new rojerusan.RSTableMetro();
        jPanel17 = new javax.swing.JPanel();
        jbBuscar = new rojeru_san.RSButtonRiple();
        jbEliminar = new rojeru_san.RSButtonRiple();
        jtfBuscar = new rscomponentshade.RSTextFieldShade();
        jPanel18 = new javax.swing.JPanel();
        rSPanelShadow2 = new rojeru_san.RSPanelShadow();
        jPanel20 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlLugar = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        jlFecha = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rSPanelShadow1 = new rojeru_san.RSPanelShadow();
        jPanel19 = new javax.swing.JPanel();
        jlImagen = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel16.setBackground(new java.awt.Color(245, 124, 0));

        jbCerrar13.setBackground(new java.awt.Color(255, 255, 255));
        jbCerrar13.setText("X");
        jbCerrar13.setColorHover(new java.awt.Color(255, 152, 0));
        jbCerrar13.setColorText(new java.awt.Color(245, 124, 0));
        jbCerrar13.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 1, 24)); // NOI18N
        jbCerrar13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCerrar13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbCerrar13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(245, 124, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jtLugares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtLugares.setColorBackgoundHead(new java.awt.Color(255, 255, 255));
        jtLugares.setColorBordeFilas(new java.awt.Color(245, 124, 0));
        jtLugares.setColorBordeHead(new java.awt.Color(245, 124, 0));
        jtLugares.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        jtLugares.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jtLugares.setColorForegroundHead(new java.awt.Color(245, 124, 0));
        jtLugares.setFuenteFilas(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtLugares.setFuenteFilasSelect(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtLugares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtLugaresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtLugares);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));

        jbBuscar.setBackground(new java.awt.Color(245, 124, 0));
        jbBuscar.setText("BUSCAR");
        jbBuscar.setColorHover(new java.awt.Color(255, 152, 0));
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(245, 124, 0));
        jbEliminar.setText("BUSCAR");
        jbEliminar.setColorHover(new java.awt.Color(255, 152, 0));
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jtfBuscar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtfBuscar.setPlaceholder("BUSCAR");
        jtfBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtfBuscarKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210)
                .addComponent(jtfBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("APELLIDO:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("LUGAR:");

        jlNombre.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("FECHA:");

        jlLugar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlApellido.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jlFecha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 851, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlLugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlLugar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        rSPanelShadow2.add(jPanel20, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));

        jlImagen.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlImagen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
        );

        rSPanelShadow1.add(jPanel19, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(rSPanelShadow1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCerrar13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCerrar13ActionPerformed
        dispose();
    }//GEN-LAST:event_jbCerrar13ActionPerformed

    private void jtLugaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtLugaresMouseClicked
        if (jtLugares.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "DEBE SELECCIONAR UNA FILA EN LA TABLA", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            control = grillaControl.getLugar(jtLugares.getSelectedRow());
            //  byte[] blob = lugar.getImagen();
            String latitud = control.getLatitud();
            String longitud = control.getLongitud();
            try {

                String imageUrl = "https://maps.googleapis.com/maps/api/staticmap?center=" + latitud + "," + longitud + "&zoom=15&size=451x291&markers=color:orange%7Clabel:S%7C" + latitud + "," + longitud + "&key=AIzaSyBiQl14RScoz5tYU5U5zhq3LD79VGkgcNs";
                Random generadorNumero = new Random();
                int numeroAleatorio = 1 + generadorNumero.nextInt(1000000);

                String destinationFile = "D:\\Documentos\\securityImagenes\\" + numeroAleatorio + ".jpg";

                //     String str = destinationFile;
                URL url = new URL(imageUrl);
                InputStream is = url.openStream();
                OutputStream os = new FileOutputStream(destinationFile);

                byte[] b = new byte[2048];
                int length;

                while ((length = is.read(b)) != -1) {
                    os.write(b, 0, length);
                }

                is.close();
                os.close();
                // jlImagen.setIcon(null);
                jlImagen.setIcon(new ImageIcon((new ImageIcon("D:\\Documentos\\securityImagenes\\" + numeroAleatorio + ".jpg")).getImage().getScaledInstance(jlImagen.getWidth(), jlImagen.getHeight(),
                        java.awt.Image.SCALE_SMOOTH)));
            } catch (IOException e) {
                e.printStackTrace();

            }

            /*   BufferedImage img = null;
                InputStream in = new ByteArrayInputStream(blob);
                try {
                    img = ImageIO.read(in);
                } catch (IOException ex) {
                    Logger.getLogger(GestionLugares.class.getName()).log(Level.SEVERE, null, ex);
                }
                Image newimage = img.getScaledInstance(jlImagen.getWidth(), jlImagen.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon icon = new ImageIcon(newimage);*/
            // JLabel jlabel = new JLabel(lugar.getNombreLugar());
            //    jlImagen.setIcon(icon);
            //jlNombreLugar.setSize(jlNombreLugar.getPreferredSize());
            // jlNombreLugar.setText(lugar.getNombreLugar());
            jlNombre.setText(control.getUsuario().getNombre());
            //jlNombreLugar.setText(lugar.getNombreLugar());
            // jlNombreLugar.validate();
            jlApellido.setText(control.getUsuario().getApellida());
            jlLugar.setText(control.getLugar().getNombreLugar());

            jlFecha.setText(control.getFechaHora());
            //jTextArea1.setEnabled(false);

        }
    }//GEN-LAST:event_jtLugaresMouseClicked

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        try {
            buscar();
            /*     if (this.jtLugares.getRowCount() < 1) {
            AlertaError er = new AlertaError(new JFrame(), true);
            er.jlError.setText("LA TABLA ESTA VACÍA");
            er.setVisible(true);
            } else {
            if (this.jtLugares.getSelectedRowCount() < 1) {
            AlertaError er = new AlertaError(new JFrame(), true);
            er.jlError.setText("SELECCIONA UN REGISTRO");
            er.setVisible(true);
            } else {
            lugar = grillaLugar.getLugar(jtLugares.getSelectedRow());
            byte[] blob = lugar.getImagen();
            {
            BufferedImage img = null;
            InputStream in = new ByteArrayInputStream(blob);
            try {
            img = ImageIO.read(in);
            } catch (IOException ex) {
            Logger.getLogger(GestionLugares.class.getName()).log(Level.SEVERE, null, ex);
            }
            ABMLugares aBMLugares = new ABMLugares(new JFrame(), true);
            Image newimage = img.getScaledInstance(aBMLugares.jlImagen.getWidth(), aBMLugares.jlImagen.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(newimage);
            aBMLugares.jlImagen.setIcon(icon);
            aBMLugares.jtfNombreLugar.setText(lugar.getNombreLugar());
            aBMLugares.jtfEmail.setText(lugar.getEmail());
            aBMLugares.jtfUbicacion.setText(lugar.getUbicacion());
            Integer id = lugar.getIdLugares();
            aBMLugares.jlId.setText(String.valueOf(id));
            if (lugar.getEstado().equals("1")) {
            aBMLugares.jrbActivo.setSelected(true);
            } else {
            aBMLugares.jrbInactivo.setSelected(false);
            
            }
            aBMLugares.jbLimpiar.setVisible(false);
            aBMLugares.jlTitulo.setText("MODIFICAR LUGAR");
            aBMLugares.jbNuevo.setText("MODIFICAR");
            aBMLugares.setVisible(true);
            
            }
            
            }
            }  */
        } catch (SQLException ex) {
            Logger.getLogger(GestionControles.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (this.jtLugares.getRowCount() < 1) {
            AlertaError er = new AlertaError(new JFrame(), true);
            er.jlError.setText("LA TABLA ESTA VACÍA");
            er.setVisible(true);
        } else {
            if (this.jtLugares.getSelectedRowCount() < 1) {
                AlertaError er = new AlertaError(new JFrame(), true);
                er.jlError.setText("SELECCIONA UN REGISTRO");
                er.setVisible(true);
            } else {
                /*   lugar = grillaLugar.getLugar(jtLugares.getSelectedRow());
                AlertaConfirmar alertaConfirmar = new AlertaConfirmar(new JFrame(), true);
                alertaConfirmar.jlId.setText(String.valueOf(lugar.getIdLugares()));
                alertaConfirmar.jlErrorPregunta.setText("¿ESTAS SEGURO?");
                alertaConfirmar.jlErrorDescripcion.setText("SE BORRARÁ PERMANENTEMENTE");
                alertaConfirmar.setVisible(true);*/
            }
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jtfBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyReleased

    }//GEN-LAST:event_jtfBuscarKeyReleased

    private void jtfBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarKeyTyped

    }//GEN-LAST:event_jtfBuscarKeyTyped
    public void buscar() throws SQLException {
        List<Control> ca = null;
        String variable = jtfBuscar.getText();
        if (!variable.isEmpty() && Character.isDigit(variable.charAt(0))) {
            try {
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");

                Date a = sdf.parse(variable);
                SimpleDateFormat fmtOut = new SimpleDateFormat("yyyy-MM-dd");
                String b = fmtOut.format(a);

                ca = controlador.buscarfecha(b);

                grillaControl = new GrillaControl((ArrayList<Control>) ca);
                //jtabla2.setModel(grillaLugar);
                jtLugares.setModel(grillaControl);

                JOptionPane.showConfirmDialog(null, b);
            } catch (ParseException ex) {
                AlertaError alertaError = new AlertaError(new JFrame(), true);
                alertaError.jlError.setText("Fecha Incorrecta");
                alertaError.setVisible(true);
                Logger.getLogger(GestionControles.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            ca = controlador.buscar(variable);

            grillaControl = new GrillaControl((ArrayList<Control>) ca);
            //jtabla2.setModel(grillaLugar);
            jtLugares.setModel(grillaControl);

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JScrollPane jScrollPane1;
    private rojeru_san.RSButtonRiple jbBuscar;
    private rojeru_san.RSButtonRiple jbCerrar13;
    private rojeru_san.RSButtonRiple jbEliminar;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlFecha;
    private javax.swing.JLabel jlImagen;
    private javax.swing.JLabel jlLugar;
    private javax.swing.JLabel jlNombre;
    public rojerusan.RSTableMetro jtLugares;
    private rscomponentshade.RSTextFieldShade jtfBuscar;
    private rojeru_san.RSPanelShadow rSPanelShadow1;
    private rojeru_san.RSPanelShadow rSPanelShadow2;
    // End of variables declaration//GEN-END:variables
}
